### PR TITLE
Allow retrieving current playback position

### PR DESCRIPTION
**Pull request by mvmn**
Allow retrieving current playback position from FFAudioInputStream

### CODE REVIEW

**Comment by mvmn** [comment]
Nevermind: turns out it's not helpful at all in detecting current playback positon.

**Comment by hendriks73** [comment]
The best way, IMHO, to get the current playback position is to call [dataLine.getMicrosecondPosition()](https://docs.oracle.com/javase/8/docs/api/javax/sound/sampled/DataLine.html#getMicrosecondPosition--) - assuming you are playing your AudioInputStream with some sort of `DataLine`.

If that's not an option, I'd recommend keeping track of how many frames you have already read form the `AudioInputStream` and convert that to seconds. Unfortunately, because of buffer sizes, that will always be a little chunky.

**Comment by mvmn** [comment]
Current dirty hack I've made is to read framePos from a PCI stream that is converted from original AudioInputStream - via reflection :-(

As for  dataLine.getMicrosecondPosition() - not sure how this will work with a seek.

**Comment by hendriks73** [comment]
> As for dataLine.getMicrosecondPosition() - not sure how this will work with a seek.

You'd have to remember your current offset, whenever you seek.

**Pull request closed without merging**
